- name: run the playbook on the localhost
  hosts: buildservers
  environment:
    PYTHONPATH: "/home/path/.local/lib/python2.7/site-packages"
  become: true
  tasks:
  - name: Install yum utils
    yum:
      name: yum-utils
      state: latest
  - name: Install device-mapper-persistent-data
    yum:
      name: device-mapper-persistent-data
      state: latest
  - name: Install lvm2
    yum:
      name: lvm2
      state: latest
  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: true
  - name: Install Docker
    package: 
      name: docker-ce
      state: latest
    become: true
  - name: Start Docker Service
    service:
      name: docker
      state: started
      enabled: yes
    become: true
  - name: Add jenkins user to docker group
    user:
      name: jenkins
      groups: docker
      append: yes
    become: true
  - name: Test Docker
    command: docker run hakkiogretmen/comparex-turkey
    become: true
  - name: Add Kubectl repo
    shell:
      cmd: |
        cat <<EOF > /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        EOF
    become: true
  - name: Install Kubectl
    command: yum install -y kubectl
    become: true
  - name: Add AzCli Repo
    shell: |
      rpm --import https://packages.microsoft.com/keys/microsoft.asc
      sh -c 'echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo'
    become: true
  - name: Install AzCli
    command: yum install -y azure-cli
    become: true
  - name: Yum Install Terraform Packages
    yum: name={{item}} state=latest
    with_items:
      - wget
  - name: Install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
      dest: /usr/bin
      remote_src: True
  - name: Install Helm
    shell: |
      curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
    become: true
